name: Build Docker image and publish it to GitHub Container Registry

on:
  push:
    branches:    
      - master

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image to the GHCR
      run: |
             docker build . --tag ghcr.io/gbdev/pandocs:latest
             docker push ghcr.io/gbdev/pandocs:latest
